
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[372] =
    {   0,
        0,    0,    0,    0,   48,   48,   53,   53,    0,    0,
        0,    0,   74,   73,   59,   60,   58,   22,   43,   73,
       21,   70,   73,   24,   25,   19,   16,   30,   17,   69,
       20,   65,   65,   31,   23,   33,   18,   32,   68,   28,
       29,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   26,   34,   27,   45,
       73,   46,   73,   49,   48,   54,   53,   53,   52,   10,
       10,   11,    9,    9,    9,   13,   13,   15,   14,   59,
       58,   36,    5,    5,   37,    0,    0,   39,   40,   72,
       50,   47,    0,   71,   71,   65,   34,   35,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   67,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   67,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   38,    0,   46,    0,    0,   44,   48,   53,
       53,    0,   51,   10,    9,    9,    9,   13,   14,    5,
       55,    0,    0,   66,    0,    0,   64,   64,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   61,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   46,    9,    7,
        5,   56,   57,    0,   64,   64,   64,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       67,   68,   68,   67,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   41,   68,   68,
       68,   68,   68,    8,    5,    0,    0,   63,   63,   64,
       68,   68,   68,   68,   68,   68,   42,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,    5,   63,   68,   68,
       68,   12,   68,   62,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,    5,   68,   68,   68,
       68,   68,    5,   68,    5,    5,   68,    5,    5,   68,
        5,    5,   68,    5,    5,   68,    5,    5,    6,    5,
        5,    5,    5,    5,    5,    3,    5,    1,    4,    2,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       28,   29,   30,   26,   26,   31,   26,   26,   32,   26,
       26,   26,   26,   26,   26,   26,   33,   26,   26,   26,
       34,   35,   36,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   26,   47,   48,   49,   50,
       51,   52,   26,   53,   54,   55,   56,   57,   58,   26,
       59,   26,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    1,    2,    1,    2,    1,    3,    1,    1,
        1,    1,    4,    1,    1,    1,    5,    1,    6,    6,
        1,    1,    1,    7,    1,    8,    8,    8,    8,    8,
        8,    8,    8,    9,   10,    9,    6,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    3,
        6,    3
    } ;

static yyconst flex_int16_t yy_base[385] =
    {   0,
        0,    0,   62,   97,  132,  168,  204,  240,  276,    0,
      338,    0,  785,  786,  782,  786,  779,  758,  786,  729,
      786,  771,  744,  786,  786,  786,  764,  786,  761,  759,
       68,   74,  109,  786,  786,  751,  750,  749,    0,  786,
      786,   37,   44,   79,  724,  363,  729,   74,  714,  145,
      727,  368,   17,  718,  109,  722,  786,   70,  786,  786,
      132,  139,  760,  786,    0,  786,  190,  752,  746,  786,
      139,  786,    0,  733,  730,  786,  145,  786,    0,  759,
      756,  786,    0,  706,  786,  748,  126,  786,  786,  740,
      786,  786,  180,  739,  214,  392,  786,  786,    0,  704,

      712,  699,  714,  709,  700,  189,  705,  692,  693,  698,
      697,  144,  696,  701,  171,   40,  700,  224,  699,  687,
      684,    0,  683,  689,  683,  689,  679,  375,  695,  677,
      678,  690,  676,  682,  675,  670,  681,  672,  677,  669,
      669,  674,  786,  233,  396,  713,  712,  711,    0,  423,
      703,  697,  786,  216,    0,  686,  680,  240,    0,  674,
      786,  701,  700,  418,  250,  253,  692,  422,  660,  669,
      664,  652,  666,  389,  665,  664,  655,  661,  657,  644,
      646,  653,  642,  638,  638,  650,  645,  635,   89,  651,
      393,  640,  641,  392,    0,  638,  632,  634,  400,  632,

      644,  625,  634,  629,   66,  632,  639,  620,  620,  406,
      632,  631,  619,  630,  624,  616,  620,  661,  637,    0,
      621,  786,  786,  439,  786,  431,  444,  617,  610,  607,
      615,  604,  600,  603,  609,  614,  601,  603,  599,  417,
      602,  601,  610,  608,  596,  597,  599,  593,  596,  588,
      597,  590,  585,  594,  581,  588,  583,  585,  591,  577,
      593,  581,  580,  589,  588,  581,  588,    0,  570,  578,
      573,  576,  579,    0,  571,  446,  448,  786,  453,  455,
      577,  568,  569,  605,  577,  572,    0,  571,  559,  566,
      559,  554,  566,  564,  555,  563,  566,  550,  559,  563,

      558,  557,  548,  556,  553,  539,  539,  550,  537,  546,
      542,  540,  548,  537,  531,  535,  546,  457,  530,  526,
      526,  786,  532,    0,  525,  535,  526,  519,  517,  513,
      518,  516,  515,  493,  504,  484,  534,  481,  489,  494,
      481,  479,  424,  468,  469,  435,  439,  428,  436,  427,
      417,  410,  405,  388,  363,  393,  233,  267,  786,  244,
      161,  137,  437,  438,  129,    0,  119,    0,    0,    0,
      786,  488,  498,  508,  517,  518,  524,  527,  534,  543,
      552,  561,  566,  569
    } ;

static yyconst flex_int16_t yy_def[385] =
    {   0,
      371,    1,  372,  372,  373,  373,  374,  374,  371,    9,
      371,   11,  371,  371,  371,  371,  371,  371,  371,  375,
      371,  371,  376,  371,  371,  371,  371,  371,  371,  371,
      371,  377,  377,  371,  371,  371,  371,  371,  378,  371,
      371,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  371,  371,  371,  371,
      379,  379,  380,  371,  381,  371,  382,  382,  371,  371,
      371,  371,  383,  383,  383,  371,  371,  371,  384,  371,
      371,  371,  375,  375,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  377,  377,  377,  371,  371,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  371,  379,  379,  380,  380,  380,  381,  382,
      382,  371,  371,  371,  383,  383,  383,  371,  384,  375,
      371,  371,  371,  371,  371,  371,  377,  377,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  380,  383,  383,
      375,  371,  371,  371,  371,  371,  377,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  383,  375,  371,  371,  371,  371,  371,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  375,  371,  378,  378,
      378,  371,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  375,  378,  378,  378,
      378,  378,  375,  378,  375,  375,  378,  375,  375,  378,
      375,  375,  378,  375,  375,  378,  375,  375,  371,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
        0,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371
    } ;

static yyconst flex_int16_t yy_nxt[849] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   39,   39,   39,   39,
       39,   39,   39,   40,   14,   41,   14,   39,   42,   43,
       44,   45,   46,   47,   39,   48,   39,   39,   39,   49,
       39,   50,   51,   52,   53,   54,   55,   56,   39,   57,
       58,   59,   14,   14,   60,  135,   14,   62,   14,  136,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       91,  102,   14,   14,   14,   92,   14,  100,  103,  101,
       93,  104,  187,   97,  105,  188,   63,   14,   14,   60,

       95,   14,   62,   14,  260,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   95,  122,   14,   14,   14,
      106,   14,  261,  123,  107,   93,  244,   96,   96,  108,
      143,   63,   14,   14,   64,   95,   14,  145,   14,  245,
       14,   14,   14,   14,  145,   14,   14,   14,   14,   14,
       95,  138,   14,   14,   14,   14,   14,  154,  154,  139,
      140,  370,  141,  158,  158,   14,  146,   14,   14,   14,
       64,  369,   14,  146,   14,  162,   14,   14,   14,   14,
      163,   14,   14,   14,   14,   14,  125,  364,   14,   14,
       14,   14,   14,  150,  182,  150,  183,  126,  164,  164,

      127,   14,  152,   14,   14,   14,   66,   67,   14,   67,
       14,  363,   14,   14,   14,   14,   69,   14,   14,   14,
       14,   14,  186,  122,   14,   14,   14,  165,   14,  166,
      371,  175,  167,  168,  154,  154,  176,   14,  145,   14,
       14,   14,   66,   67,   14,   67,   14,  362,   14,   14,
       14,   14,   69,   14,   14,   14,   14,   14,  158,  158,
       14,   14,   14,  190,   14,  191,  165,  146,  225,  226,
      361,  225,  226,   14,  360,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   70,   71,   14,   72,   14,   14,

       14,   73,   73,   73,   74,   73,   75,   73,   73,   14,
       14,   14,   14,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   76,   77,   14,   78,
       14,   14,   14,   79,   79,   79,   79,   79,   79,   79,
       79,   14,   14,   14,   14,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   14,   14,   14,

      110,  145,  111,  359,  112,  113,  114,  129,   93,  130,
       96,   96,  358,  115,  116,  117,  118,  119,   95,  131,
      120,  132,  133,  200,  201,  134,  150,  357,  150,  202,
      146,  251,  203,   95,  247,  152,  164,  164,  371,  254,
      227,  227,  230,  231,  224,  122,  356,  248,  266,  280,
      280,  355,  276,  122,  277,  267,  122,  278,  279,  224,
      371,  276,  227,  227,  278,  279,  278,  279,  291,  354,
      122,  318,  318,  280,  280,  318,  318,  345,  346,  365,
      367,  353,  352,  351,  350,  349,  366,  368,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   83,  348,
      347,  122,   83,  122,   83,   86,  344,   86,   94,   94,
      122,   94,   99,  122,   99,  144,  144,  343,  342,  144,
      144,  144,  144,  144,  147,  147,  122,  341,  147,  147,
      147,  147,  147,  149,  149,  149,  122,  149,  122,  149,
      122,  149,  151,  151,  151,  122,  151,  151,  151,  122,
      151,  155,  122,  155,  159,  122,  159,  122,  122,  340,
      122,  339,  338,  337,  336,  335,  334,  122,  122,  333,
      122,  122,  122,  332,  331,  122,  122,  122,  122,  122,

      330,  122,  122,  329,  122,  328,  122,  327,  326,  325,
      122,  122,  122,  324,  323,  322,  321,  320,  319,  317,
      122,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  122,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  122,  295,  122,  294,  293,  122,  122,
      292,  122,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  122,  281,  122,  275,  274,  218,  273,  272,  271,
      122,  270,  269,  268,  265,  264,  263,  262,  259,  258,
      257,  256,  255,  253,  252,  122,  250,  249,  246,  243,
      242,  241,  240,  239,  238,  122,  237,  236,  122,  235,

      234,  233,  232,  229,  122,  122,  228,  122,  371,  223,
      222,  221,  220,  219,  153,  371,  218,  218,  148,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  199,  198,  197,  196,  195,  194,  193,
      192,  189,  185,  184,  181,  180,  179,  178,  177,  174,
      173,  172,  171,  170,  169,  371,   90,  161,  160,   81,
       80,  157,  156,  153,  371,  148,  142,  137,  128,  124,
      121,  109,   97,   98,   97,   90,   89,   88,   87,   85,
       84,   82,   81,   80,  371,   13,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371
    } ;

static yyconst flex_int16_t yy_chk[849] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,   53,    3,    3,    3,   53,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
       31,   43,    3,    3,    3,   31,    3,   42,   43,   42,
       32,   43,  116,   58,   43,  116,    3,    4,    4,    4,

       32,    4,    4,    4,  205,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,   32,   48,    4,    4,    4,
       44,    4,  205,   48,   44,   33,  189,   33,   33,   44,
       58,    4,    5,    5,    5,   33,    5,   61,    5,  189,
        5,    5,    5,    5,   62,    5,    5,    5,    5,    5,
       33,   55,    5,    5,    5,    5,    5,   71,   71,   55,
       55,  367,   55,   77,   77,    5,   61,    5,    6,    6,
        6,  365,    6,   62,    6,   87,    6,    6,    6,    6,
       87,    6,    6,    6,    6,    6,   50,  362,    6,    6,
        6,    6,    6,   67,  112,   67,  112,   50,   93,   93,

       50,    6,   67,    6,    7,    7,    7,    7,    7,    7,
        7,  361,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,  115,  115,    7,    7,    7,   95,    7,   95,
       95,  106,   95,   95,  154,  154,  106,    7,  144,    7,
        8,    8,    8,    8,    8,    8,    8,  360,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,  158,  158,
        8,    8,    8,  118,    8,  118,  166,  144,  165,  165,
      358,  166,  166,    8,  357,    8,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       46,  145,   46,  356,   46,   46,   46,   52,   96,   52,
       96,   96,  355,   46,   46,   46,   46,   46,   96,   52,
       46,   52,   52,  128,  128,   52,  150,  354,  150,  128,
      145,  194,  128,   96,  191,  150,  164,  164,  168,  199,
      168,  168,  174,  174,  164,  194,  353,  191,  210,  226,
      226,  352,  224,  199,  224,  210,  240,  224,  224,  164,
      227,  277,  227,  227,  276,  276,  277,  277,  240,  351,
      240,  279,  279,  280,  280,  318,  318,  343,  343,  363,
      364,  350,  349,  348,  347,  346,  363,  364,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  375,  345,
      344,  342,  375,  341,  375,  376,  340,  376,  377,  377,
      339,  377,  378,  338,  378,  379,  379,  337,  336,  379,
      379,  379,  379,  379,  380,  380,  335,  334,  380,  380,
      380,  380,  380,  381,  381,  381,  333,  381,  332,  381,
      331,  381,  382,  382,  382,  330,  382,  382,  382,  329,
      382,  383,  328,  383,  384,  327,  384,  326,  325,  323,
      321,  320,  319,  317,  316,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,

      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  286,  285,  284,  283,  282,  281,  275,
      273,  272,  271,  270,  269,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  221,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  209,  208,  207,  206,  204,  203,
      202,  201,  200,  198,  197,  196,  193,  192,  190,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,

      177,  176,  175,  173,  172,  171,  170,  169,  167,  163,
      162,  160,  157,  156,  152,  151,  148,  147,  146,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,
      131,  130,  129,  127,  126,  125,  124,  123,  121,  120,
      119,  117,  114,  113,  111,  110,  109,  108,  107,  105,
      104,  103,  102,  101,  100,   94,   90,   86,   84,   81,
       80,   75,   74,   69,   68,   63,   56,   54,   51,   49,
       47,   45,   38,   37,   36,   30,   29,   27,   23,   22,
       20,   18,   17,   15,   13,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hw3.l"
#line 2 "hw3.l"
#include <stdio.h>
#include "y.tab.h"
#include "define.h"
#include "SymbolTable.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <malloc.h>

char *copys();

void insert_printline(char* yytext, int length);
void print_line();

//  indicate line now
int	lineCount = 1;
int I = 0;

char line_array[3000];

int line_start = 0;
int line_end = 0;
char* yytext_string;

extern FILE *f_asm;	

// 0 off 1 on
//int source_condition = 1;
//int token_condition = 1;
int source_condition = 1;
int token_condition = 0;







#line 809 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT_A 2
#define COMMENT_B 3
#define DIGITALWRITE 4
#define DELAY 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 56 "hw3.l"



#line 1005 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 372 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 786 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 "hw3.l"
{source_condition = 1; insert_printline(yytext, strlen(yytext));}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "hw3.l"
{source_condition = 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "hw3.l"
{token_condition = 1; insert_printline(yytext, strlen(yytext));}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "hw3.l"
{token_condition = 0; insert_printline(yytext, strlen(yytext));}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "hw3.l"
{fprintf(stderr, "Error at line %d: %s\n", lineCount, yytext);exit(1);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "hw3.l"
{
        /* Special function from Andes */
        BEGIN(DIGITALWRITE);
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "hw3.l"
{
        fprintf(f_asm, "    movi $r1, 0\n");
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 79 "hw3.l"
{
        fprintf(f_asm, "    movi $r1, 1\n");

    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "hw3.l"
{
        int index = look_up_symbol(yytext);

        /* Load to r0 */
        switch(table[index].mode)
        {
            case ARGUMENT_MODE:
                fprintf(f_asm, "    lwi $r0, [$sp+%d]\n",table[index].offset*4);
                break;
            case LOCAL_MODE:
                fprintf(f_asm, "    lwi $r0, [$sp+%d]\n",table[index].offset*4);
                break;
            /* global */
        }
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "hw3.l"
{
        int num = atoi(yytext);
        fprintf(f_asm, "    movi $r0, %d\n",num);
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 104 "hw3.l"
{
        fprintf(f_asm, "    bal digitalWrite\n");
        BEGIN(INITIAL);
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "hw3.l"
{
        /* Special function from Andes */
        BEGIN(DELAY);
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 114 "hw3.l"
{
        int num = atoi(yytext);
        fprintf(f_asm, "    movi $r0, %d\n",num);
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 119 "hw3.l"
{
        int index = look_up_symbol(yytext);

        /* Load to r0 */
        switch(table[index].mode)
        {
            case ARGUMENT_MODE:
                fprintf(f_asm, "    lwi $r0, [$sp+%d]\n",table[index].offset*4);
                break;
            case LOCAL_MODE:
                fprintf(f_asm, "    lwi $r0, [$sp+%d]\n",table[index].offset*4);
                break;
            /* global */
        }
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "hw3.l"
{
        fprintf(f_asm, "    bal delay\n");
        BEGIN(INITIAL);
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 143 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('+');
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 150 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('-');
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 157 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('=');
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 164 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('*');
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 171 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('/');
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 178 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('%');
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 185 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('!');
			}			
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 193 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return(';');
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 200 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return('(');                  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 205 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(')');                  }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 210 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return('{');                  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 215 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));;
                          return('}');                  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 220 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return('[');                  }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 225 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(']');                  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 230 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(',');                  }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 235 "hw3.l"
{ if (token_condition == 1)
				fprintf(stdout, "#punc:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(':');                  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 241 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('>');  
			}					
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 249 "hw3.l"
{
				if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
				return('<');  
			}	
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 257 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(ARITHCOMPARE);         }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 262 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(ARITHCOMPARE);         }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 266 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(ARITHCOMPARE);         }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 271 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(ARITHCOMPARE);         }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 276 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(ARITHCOMPARE);         }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 281 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(DOUBLEDOUBLE);         }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 286 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#op:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(DOUBLEDOUBLE);         }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 291 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#key:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(TRUEFALSE);         }		
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 296 "hw3.l"
{ if (token_condition == 1)
					fprintf(stdout, "#key:%s\n", yytext);
				insert_printline(yytext, strlen(yytext));
                          return(TRUEFALSE);         }								  
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 303 "hw3.l"
{
				insert_printline(yytext, strlen(yytext)); 
				//printf("start string!\n");
				BEGIN STRING;
			}		
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 312 "hw3.l"
{
			fprintf(stderr, "Error at line %d: %s\n", lineCount, yytext); exit(1);
			}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 316 "hw3.l"
{
			fprintf(stderr, "Error at line %d: %s\n", lineCount, yytext); exit(1);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 320 "hw3.l"
{
			
			yytext_string = (char *)malloc(3000 * sizeof(char));
		
			strncpy(yytext_string , yytext, strlen(yytext) - 1);
			if (token_condition == 1)
				fprintf(stdout, "#string:%s\n", yytext_string);
			insert_printline(yytext, strlen(yytext)); 
			
			//printf("strlen(yytext) - 1 = %d\n", strlen(yytext) - 1);
			//printf("end string!\n");
			
			BEGIN 0;
			yylval.token= atoi(yytext);
			return String;
			
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 340 "hw3.l"
{
				insert_printline(yytext, strlen(yytext));
				BEGIN COMMENT_A;
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 344 "hw3.l"
{
			insert_printline(yytext, strlen(yytext)); 
			}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 348 "hw3.l"
{
			print_line();
			BEGIN 0;
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 353 "hw3.l"
{
				insert_printline(yytext, strlen(yytext));
			//printf("Start comment B\n");		
			BEGIN COMMENT_B;
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 359 "hw3.l"
{
			insert_printline(yytext, strlen(yytext)); 
			//printf("End comment B\n");
			BEGIN 0;
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 364 "hw3.l"
{
			insert_printline(yytext, strlen(yytext));
			BEGIN COMMENT_B;
	      }	
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 368 "hw3.l"
{
			//printf("start comment B\n");	
			insert_printline(yytext, strlen(yytext)); 
				BEGIN COMMENT_B;
			}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 374 "hw3.l"
{
			print_line();
			
				BEGIN COMMENT_B;
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 383 "hw3.l"
{
			if (token_condition == 1)
				fprintf(stdout, "#char:%s\n", yytext);
			insert_printline(yytext, strlen(yytext));
			//yylval.charv = atoi(yytext);
			//return CHAR;
				return CONSTANT;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 392 "hw3.l"
{
			if (token_condition == 1)
				fprintf(stdout, "#char:%s\n", yytext);
			insert_printline(yytext, strlen(yytext));				
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 398 "hw3.l"
{
			if (token_condition == 1)
				fprintf(stdout, "#char:%s\n", yytext);
			insert_printline(yytext, strlen(yytext));				
			}		
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 407 "hw3.l"
{insert_printline(yytext, strlen(yytext));}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 408 "hw3.l"
{insert_printline(yytext, strlen(yytext));}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 409 "hw3.l"
{print_line();}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 410 "hw3.l"
{	if (token_condition == 1)
					printf("#key:int\n"); 
				insert_printline(yytext, strlen(yytext));
				int value = id_or_keyword(yytext);
				return(value);
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 416 "hw3.l"
{
				if (token_condition == 1)
					printf("#key:double\n"); 
				insert_printline(yytext, strlen(yytext));
				int value = id_or_keyword(yytext);
				return(value);
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 424 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#sci:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
	yylval.token= atoi(yytext);
	return CONSTANT;
}	
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 432 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#sci:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
	yylval.token= atoi(yytext);
	return CONSTANT;
}	
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 442 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#integer:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
	
	yylval.token= atoi(yytext);
	return CONSTANT;
	}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 451 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#double:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
	yylval.token= atoi(yytext);
	return CONSTANT;
	}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 460 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#key:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
	
	//hw2
	int value = id_or_keyword(yytext);
	return(value);
	
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 472 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#id:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
	int value;
	value = IDENTIFIER;	
    yylval.ident= copys(yytext);
	return(value);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 482 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#punc:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 490 "hw3.l"
{
	if (token_condition == 1)
		fprintf(stdout, "#op:%s\n", yytext);
	insert_printline(yytext, strlen(yytext));
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 497 "hw3.l"
{fprintf(stderr, "Error at line %d: %s\n", lineCount, yytext);exit(1);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 501 "hw3.l"
{
    fprintf(stderr, "Error at line %d: %s\n", lineCount, yytext);
    exit(1);
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 507 "hw3.l"
ECHO;
	YY_BREAK
#line 1739 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(COMMENT_A):
case YY_STATE_EOF(COMMENT_B):
case YY_STATE_EOF(DIGITALWRITE):
case YY_STATE_EOF(DELAY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 372 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 372 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 371);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 507 "hw3.l"



int id_or_keyword(char* text)
{
 int i;
 for (i=0; i<(sizeof(k_tab)/sizeof(KWORD)); i++) {
    if (!strcmp(text, k_tab[i].name))
       return k_tab[i].value;
 }
}





int yywrap() {
	return 1; 
}

void insert_printline(char* yytext, int length){
	int i;
	int j = 0;
	for (i = line_end; i < line_end + length; i++){
		line_array[i] = yytext[j];
		j++;
	}
	line_end += length;	
}

void print_line(){
	int i;
	
	if (source_condition == 1){
	
		printf("%d:", lineCount);
		
		for (i = line_start; i < line_end; i++){
			printf("%c", line_array[i]);
		}
		printf("\n");
	}
	lineCount++;
	line_start = line_end;
	
}

char   *
copyn(n, s)
	register int n;
	register char *s;
{
	register char *p, *q;
	//char   *calloc();

	p = q = calloc(1,n);
	while (--n >= 0)
		*q++ = *s++;
	return (p);
}

char   *
copys(s)
	char   *s;
{
	return (copyn(strlen(s) + 1, s));
}


